[tool.ruff]
line-length = 120

lint.select = ["E", "F", "I", "UP"]
lint.ignore = ["E501"]

exclude = [
  ".venv",
  "data",
  ".git",
  ".ruff_cache",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.ruff.lint.isort]
known-first-party = ["dags"]
