# pyproject.toml
[tool.ruff]
line-length = 120

# 어떤 규칙을 검사할지 설정
lint.select = ["E", "F", "I", "UP"]
lint.ignore = ["E501"] # 긴 줄 허용 (formatter가 자동 정리하므로 lint에서는 무시)

# 무시할 경로
exclude = [
  ".venv",
  "data",
  ".git",
  ".ruff_cache",
]

[tool.ruff.format]
# Black 스타일 기반 포매팅
quote-style = "double"
indent-style = "space"

[tool.ruff.lint.isort]
# import 정렬 설정
known-first-party = ["dags"]
